### ISSUE TITLE
Erreur search.php

### ISSUE THREAD

**Issue by cookaxy** [llaumgui/fluxsphinx#1]
Premiere erreur : 
sphinx.php : setForumsfilter -> search.php setForumsFilter
Erreur de nomination de function

Deuxieme erreur : 
Pour la recherche par pseudo uniquement cela ne fonctionne tout simplement pas.
Une erreur comme quoi l'objet sphinx n'existe pas. Mais meme une fois créé ceela ne fonctionne toujours pas.

Cordialement

**Comment by llaumgui** [comment]
J'ai pris un peu de retard (nouveau PC) j'oublie pas.

**Comment by cookaxy** [comment]
Du nouveau ?

**Comment by llaumgui** [comment]
Oui ma stack DAMP (Docker Apache MySQL PHP) est up me reste plus qu'à rajouter Sphinx et je m'y met :;)

**Comment by llaumgui** [comment]
Ca avance...

**Comment by DarkZeroCD** [comment]
ça se présente bien ?

**Comment by llaumgui** [comment]
Oui, c'est corrigé sur Fedora-FR : http://forums.fedora-fr.org/search.php
Je fais des derniers tests, je fait un merge avec la dernière version de FluxBB et je commit...

**Comment by llaumgui** [comment]
Fixed !
