### ISSUE TITLE
Sphinx : some settings have been removed

### ISSUE THREAD

**Issue by DarkZeroCD** [llaumgui/fluxsphinx#2]
Hello,

With the latest version of Sphinx, some settings have been removed. This does not prevent working, but maybe update the conf?

Are these parameters important?

```
WARNING: key 'port' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: index 'fluxbb_search_posts_main': prefix_fields and infix_fields has no effect with dict=keywords, ignoring
```

For port, it is the **9312**, by default.

For other settings I prefer to ask you if this is important.

Thank you in advance.

**Comment by llaumgui** [comment]
Hi,

can you do a Pull Request ?

Thx.

**Comment by DarkZeroCD** [comment]
Hi,

I'm not a GitHub user, I don't know how to make a pull-request.
I have not solved the problems, I have not touched the parameters and it works.
It's just better to have an explanation from the author of the project and why not correct them ^^

Thank you for taking the time;)
